# Generated by Django 2.1.2 on 2018-11-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=12, null=True)),
                ('address', models.CharField(default=None, max_length=250, null=True)),
                ('is_aproved', models.BooleanField(default=False)),
                ('card_number', models.CharField(max_length=16)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='main.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='main.Salon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
