# Generated by Django 2.1.2 on 2018-11-21 16:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_salon_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliet_comments', to='main.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_aproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_masters', to='main.Master')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('time', models.TimeField()),
                ('flag', models.CharField(choices=[('new_order', 'new_order'), ('canceled_order', 'canceled_order'), ('service_rendered', 'service_rendered'), ('service_paid', 'service_paid')], default='new_order', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='main.Client')),
                ('master_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_price', to='main.MasterService')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_orders', to='main.Partner')),
            ],
        ),
        migrations.AddField(
            model_name='salon',
            name='work_end',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='work_start',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterservice',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_master_services', to='main.Salon'),
        ),
        migrations.AddField(
            model_name='masterservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='main.Service'),
        ),
        migrations.AddField(
            model_name='master',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='main.Salon'),
        ),
        migrations.AddField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_comments', to='main.Master'),
        ),
        migrations.AddField(
            model_name='comment',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_comments', to='main.Partner'),
        ),
        migrations.AddField(
            model_name='comment',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_comments', to='main.Salon'),
        ),
    ]
