# Generated by Django 2.1.2 on 2018-11-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181123_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
