# Generated by Django 2.1.2 on 2018-11-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_client_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='salon',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
