# Generated by Django 2.1.2 on 2018-11-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181123_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='work_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='salon',
            name='work_start',
            field=models.TimeField(),
        ),
    ]
