# Generated by Django 2.1.2 on 2019-05-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181123_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='img_url',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='img_url',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
