# Generated by Django 2.1.2 on 2019-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190514_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
